### PR TITLE
std: power of two

### PR DESCRIPTION
**Pull request by MCJOHN974**
zkevm-rom use similar [function](https://github.com/0xPolygonHermez/zkevm-rom/blob/877328eff50070426f040a8843b7d6eb3140ef22/main/2-exp.zkasm#L4) for powers

### CODE REVIEW

**Comment by MCJOHN974** [comment]
Maybe it will be useful add this function only in programs which contain instruction which use it. OTOH du of ``zkasm_data`` is 6MB which don't looks like a lot and almost each real program have ``shl\r``, so maybe it's ok to keep this

**Review by akashin — CHANGES_REQUESTED** [review]
Let's investigate whether we can avoid duplication by using an `IMPORT`

**Comment by MCJOHN974** [comment]
> Let's investigate whether we can avoid duplication by using an `IMPORT`

[Done](https://github.com/near/wasmtime/pull/111/commits/3728ad374254ecea27d65b07204d648581583ac6)! Also, it works only if I place include in the end of program, if I place in the beginning it leads to infinite loop (zkasm don't search for ``start`` label and just starts execution from the first line(?))

**Review by akashin — APPROVED** [review]
Overall LGTM.

How does this change affect the number of counters used by the generated `.zkasm` programs? Ideally, we want to make sure we're not adding overhead to the programs that are not using this feature ("pay for what you use")

**Comment by MCJOHN974** [comment]
> Overall LGTM.
> 
> How does this change affect the number of counters used by the generated `.zkasm` programs? Ideally, we want to make sure we're not adding overhead to the programs that are not using this feature ("pay for what you use")

In next PR I will make this import added only to code which contains instructions which use this function.

**Pull request merged**
