### PR TITLE
housekeeping: developer cli

### LINKED ISSUE #116: Make convinent developer CLI
It will be nice to have short and simple commands to do next list of things

 - compile_all
 - run_one <filename> (and print verbose error)
 - run_all (and print list of changed statuses)
 - update_csv (run all and update all csv's)

### PR DESCRIPTION
**Pull request by MCJOHN974**
Here I tried to gather all commands I frequently use in one place. Fixes #116

### CODE REVIEW

**Comment by MCJOHN974** [comment]
Two questions for reviewers:
1) Does anybody know way to run only one zkasm file with verbose output?
2) Does anybody know scenario when we locally compile without ``env UPDATE_EXPECT=1 ``?

**Comment by MCJOHN974** [comment]
Also, using python make usage of script 8 key pressings longer, but I so love what python argparse do, comparing to bash, so...

**Comment by mooori** [comment]
> Does anybody know way to run only one zkasm file with verbose output?

I haven’t tried it yet.

> Does anybody know scenario when we locally compile without env UPDATE_EXPECT=1 ?

Possibly when doing a refactor which should _not_ change generated zkASM.

> Any other commands we want to see here?

Looks complete to me. Though keep in mind that I’m relatively new to working with this repo.

**Review by mooori — APPROVED** [review]
This will be helpful, thanks @MCJOHN974! So far I’ve been keeping local Makefiles with commands I’m currently using. Having this cli instead provides a better dev experience.

LGTM overall. I didn’t write Python in a while, though, so can’t judge any Python specifics.

**Review by nagisa — COMMENTED** [review]
Would it not be a good idea to use the same tooling we use in nearcore (`Justfile` in particular) rather than writing our own python scripts for this (and even if we did not use `just` – why a python script over something like a makefile?)

**Comment by MCJOHN974** [comment]
Since we will significantly rework testing and benchmarking, this code no longer needed. But I think it will be nice to have such cli once changes in testing and benchmarking will land

**Pull request closed without merging**
